# Generated by Django 3.0.3 on 2020-02-28 09:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('degree', models.TextField()),
                ('subject', models.TextField()),
                ('last_update', models.DateField(default=datetime.date.today)),
                ('average_valoration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DNI', models.TextField()),
                ('name', models.TextField()),
                ('mail', models.EmailField(max_length=254)),
                ('starting_year', models.DateField()),
                ('subjects', models.TextField()),
                ('average_valoration', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notehub.Document')),
                ('unit', models.IntegerField()),
                ('corrected', models.BooleanField(default=False)),
            ],
            bases=('notehub.document',),
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notehub.Document')),
                ('unit', models.IntegerField()),
                ('date', models.DateField()),
                ('schematization_degree', models.IntegerField()),
            ],
            bases=('notehub.document',),
        ),
        migrations.CreateModel(
            name='Valoration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('comment', models.TextField()),
                ('date', models.DateField()),
                ('document', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='notehub.Document')),
                ('student', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='notehub.Student')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='notehub.Student'),
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notehub.Document')),
                ('date', models.DateField()),
                ('solved', models.BooleanField(default=False)),
                ('exercices', models.ManyToManyField(to='notehub.Exercice')),
            ],
            bases=('notehub.document',),
        ),
    ]
