# Generated by Django 3.0.3 on 2020-02-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notehub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='subjects',
        ),
        migrations.AlterField(
            model_name='student',
            name='average_valoration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
